config/routes.rb
Rails.application.routes.draw do
  get 'coaching_controller/answer'

  get 'coaching_controller/ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller_controller.rb
class CoachingControllerController < ApplicationController
  def ask
  end

  def answer
    @question = params[:user_question]
    @answer = coach_answer_enhanced(@question)
  end

  private

  def coach_answer(your_message)
    # TODO: return coach answer to your_message
    if your_message == "I am going to work right now!"
      return ""
    elsif your_message.include? "?"
      return "Silly question, get dressed and go to work!"
    else
      return "I don't care, get dressed and go to work!"
    end
  end

  def coach_answer_enhanced(your_message)
    if your_message.downcase == "i am going to work right now!"
      return ""
    elsif your_message == your_message.upcase
      answer = coach_answer(your_message)
      return "I can feel your motivation! #{answer}"
    else
      return coach_answer(your_message)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_controller_helper.rb
module CoachingControllerHelper
end

app/views/coaching_controller/answer.html.erb
<h1>Silly fucker</h1>
<div>
  <p> <%= @question %></p>
</div>
<div>
  <p> <%= @answer %></p>
</div>




<%= link_to "Ask another question BITCH!", coaching_controller_ask_path %>

app/views/coaching_controller/ask.html.erb
<form action="/coaching_controller/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="user_question" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>